### ISSUE TITLE
Request: translations for keywords used in the widget

### ISSUE THREAD

**Issue by Crow74** [AuraQ/BootstrapMultiSelectForMendix#1]
First of all: I love the widget! Thank you very much for developing this. It is really useful.

Could you make it possible to make certain keywords/labels translatable or have translations added for different languages?

For example: when no elements are selected, the widget shows *None selected*. I would like to show a Dutch label here, like *Geen selectie*. If you need assistance with including Dutch labels, I would be glad to help you out.

An alternative would be to make properties for the labels in the widget so the developers can decide themselves what texts they want to use in their project.

**Comment by lindski** [comment]
Thanks :)

Sure, I can add some additional translations... these are the strings that we can define translations for:

"Select All"
"None selected"
"All selected"
"{0} selected" ({0} will be replaced by the number of selected items)

If you can provide the Dutch strings I will add them in

**Comment by Crow74** [comment]
Thank you for your quick response!

Here are the Dutch translations for the labels:

"Select All" > "Alles selecteren"
"None selected" > "Niets geselecteerd"
"All selected" > "Alles geselecteerd"
"{0} selected" > "{0} geselecteerd"

As you can see I changed my mind on the "None selected" label. :wink:

**Comment by lindski** [comment]
Dutch translations added in commit 8d3b01b96af394f51bcde19ff1096008578999a4

The Test project has been updated to include Dutch language and the mpk in the dist has also been updated for you to use in your own app.

I'll also create a new release and update the widget in the app store

**Comment by Crow74** [comment]
Works like a charm!
Thanks again for your quick changes!
