### ISSUE TITLE
Conditional Visibility - Display issues

### ISSUE THREAD

**Issue by dan-lawford** [AuraQ/BootstrapMultiSelectForMendix#10]
I have a multi select within a conditional visibility container, when the multi select is within the container it causes a display issue where I am unable to select anything from the list as shown in the attached screenshot. I Have tested the same multi select outside of the conditional visibility and works as expected.

![multiselect-issue](https://user-images.githubusercontent.com/12201009/27033794-cbf704f6-4f72-11e7-98fc-5d98b7c5fedd.PNG)

**Comment by lindski** [comment]
Looks like this is related to a known issue in 7.3.0. Can you retest when 7.4.0 is released and let me know if you are still having the same problem?

**Comment by lindski** [comment]
Not able to reproduce this

Feel free to re-open the issue if you still think it is a problem.
