### ISSUE TITLE
Issue with ampersands (&) in labels of dropdown select values

### ISSUE THREAD

**Issue by Crow74** [AuraQ/BootstrapMultiSelectForMendix#2]
I have noticed that when a display attribute value of the queried reference set contains an ampersand (&), the dropdown list shows the ampersand in the browser as "& amp ;".

So a selectable value of "Psyche & Brain" ends up in the dropdown as "Psyche & amp ; Brain".

Note: I had to write "& amp ;" in this comment with spaces between "&", "amp" and ";" because Github converts it to an ampersand when writing this string without spaces. :grimacing:

**Comment by lindski** [comment]
The option labels were being escaped incorrectly... I have removed this in commit 304216728e796fca73aea04d829cbecd2123af0f

Test project contains a new test for special characters or you can take the new mpk in the dist folder to test this in your own app
