### ISSUE TITLE
Allow multiple instances which use the same Entity, but over different associations

### ISSUE THREAD

**Issue by dkho87** [AuraQ/BootstrapMultiSelectForMendix#4]
Running Mendix 6.3.1:

Something seems to go wrong whenever the widget is added to a page twice. Our scenario: Dataview of entity Report with reference sets to Account and Company.

If I add only 1 instance of the widget (e.g. one that uses the Report_Account association), everything works fine. As soon as I add a second instance on that same page which uses the Report_Company association, upon opening of the page "An error has occurred while handling the request." is thrown in the browser.

Everybody has read & write access to all entities and attributes involved.

**Comment by lindski** [comment]
Are you using the latest release of the widget?

Do you have a test project you can share with me that demonstrates the problem? 

I've created a sandbox app in 6.3.1 using the module's test project, available here: https://bsmstest.mxapps.io/index.html, but I'm not able to reproduce this in the Multiple Instances page

**Comment by dkho87** [comment]
Apologies for the late reply. There seems to be something project specific going on that is causing this error. I was not able to reproduce the error in a fresh project. I'll close this issue for now. Thanks for having a look!
