### ISSUE TITLE
Ability to search on options from the drop down

### ISSUE THREAD

**Issue by siddiqui111** [AuraQ/BootstrapMultiSelectForMendix#5]
Can we have the ability to search from the drop down instead of scrolling a long list to make multiple selection and we should be able to configure the widget to turn it on or off?

**Comment by lindski** [comment]
Two new properties have been added to the Display tab in commit 6c90a1b:

**Add Filter**, which controls whether the search filter should be displayed at the top of the dropdown.
**Case Sensitive Filter**, which controls whether the search is case sensitive or not

**Comment by lindski** [comment]
This is now available in the app store
