### ISSUE TITLE
Ability to add/ remove progress bar on onchange event microflow

### ISSUE THREAD

**Issue by siddiqui111** [AuraQ/BootstrapMultiSelectForMendix#6]
If I have a long onchange microflow that does some complex changes on selection then i want the ability to add a progress bar so that user know they have to wait (currently its annoying that user don;t know what's happening and widget become unresponsive until the onchange microflow is completed). Can this progress bar be configured in the widget to turn it on/off under onchange tab?

**Comment by lindski** [comment]
Two new properties have been added to the Events tab in commit 5f578ca :

**Show Progress Bar**, which controls whether a progress bar should be displayed when executing the onchange microflow.
**Progress Message**, which, if populated, is used as the message for the progress bar

**Comment by lindski** [comment]
This is now available in the app store
