### ISSUE TITLE
Ability to add display attribute of any data type

### ISSUE THREAD

**Issue by siddiqui111** [AuraQ/BootstrapMultiSelectForMendix#7]
Currently I can only select string as display attribute but it is possible if we can have any data type that can be selected as display attribute ?

**Comment by lindski** [comment]
I've added basic templating in commit 75aa03b which allows you to define a template using multiple attributes (AutoNumber, String, Enum, Integer, Float, Currency, Decimal, Long and DateTime)

The Display Attribute property has been replaced by Display Template and Template Attributes has been added to define the data to display

Needs to add some additional test cases but there is a copy available in the test project if you want to take a look.

**Comment by lindski** [comment]
This is now available in the app store
