### ISSUE TITLE
Handle feedback validation message based on selection 

### ISSUE THREAD

**Issue by siddiqui111** [AuraQ/BootstrapMultiSelectForMendix#8]
I have feedback validation message on association and whenever user tries to search on empty selection then this validation message will be displayed (if association is empty). I expected once the selection is made widget will remove the validation message automatically but it doesn't even if the object is refreshed as part of onchange event. Please can this validation check be handled in the widget?

**Comment by lindski** [comment]
There was an error in the widget's subscriptions.

This should now be fixed by commit a9d5428

**Comment by lindski** [comment]
This is now available in the app store
